// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"encoding"

	"github.com/pkg/errors"
	"go.uber.org/zap/zapcore"
)

type Chunk interface {
	encoding.BinaryMarshaler
	zapcore.ObjectMarshaler
	Header() ChunkHeader
	Data() []byte
}

type chunk struct {
	header ChunkHeader
	data   []byte
}

func NewChunk(
	header ChunkHeader,
	data []byte,
) Chunk {
	return &chunk{
		header: header,
		data:   data,
	}
}

func (m chunk) Header() ChunkHeader {
	return m.header
}
func (m chunk) Data() []byte {
	return m.data
}

func (m chunk) MarshalLogObject(enc zapcore.ObjectEncoder) error {
	if err := enc.AddObject("header", m.Header()); err != nil {
		return errors.Wrap(err, "failed to AddObject header")
	}
	enc.AddInt("dataLength", len(m.Data()))
	return nil
}
