// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type NetConnectionCommandHandler interface {
	OnConnect(ctx context.Context, connect Connect) ConnError
	OnConnectResult(ctx context.Context, connectResult ConnectResult) ConnError
	OnConnectError(ctx context.Context, connectError ConnectError) ConnError
	OnCall(ctx context.Context, call Call) ConnError
	OnCallResponse(ctx context.Context, callResponse CallResponse) ConnError
	OnClose(ctx context.Context, close Close) ConnError
	OnCreateStream(ctx context.Context, createStream CreateStream) ConnError
	OnCreateStreamResult(ctx context.Context, createStreamResult CreateStreamResult) ConnError
	OnCreateStreamError(ctx context.Context, createStreamError CreateStreamError) ConnError
}
