// Code generated by "stringer -type VideoFunctionFlag -trimprefix VideoFunctionFlag -output cmd_netconnection_video_function_flag_string_gen.go"; DO NOT EDIT.

package rtmp

import "strconv"

const _VideoFunctionFlag_name = "ClientSeek"

var _VideoFunctionFlag_index = [...]uint8{0, 10}

func (i VideoFunctionFlag) String() string {
	i -= 1
	if i >= VideoFunctionFlag(len(_VideoFunctionFlag_index)-1) {
		return "VideoFunctionFlag(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _VideoFunctionFlag_name[_VideoFunctionFlag_index[i]:_VideoFunctionFlag_index[i+1]]
}
