// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type NetConnectionCommandHandler interface {
	OnConnect(ctx context.Context, connect Connect)
	OnConnectResult(ctx context.Context, connectResult ConnectResult)
	OnConnectError(ctx context.Context, connectError ConnectError)
	OnCall(ctx context.Context, call Call)
	OnCallResponse(ctx context.Context, callResponse CallResponse)
	OnClose(ctx context.Context, close Close)
	OnCreateStream(ctx context.Context, createStream CreateStream)
	OnCreateStreamResult(ctx context.Context, createStreamResult CreateStreamResult)
	OnCreateStreamError(ctx context.Context, createStreamError CreateStreamError)
}
