// Code generated by "stringer -type AudioCodecFlag -trimprefix AudioCodecFlag -output cmd_netconnection_audio_codec_flag_string_gen.go"; DO NOT EDIT.

package rtmp

import "strconv"

const _AudioCodecFlag_name = "NoneAdpcmMp3IntelUnusedNelly8NellyG711aG711uNelly16AacSpeexAll"

var _AudioCodecFlag_map = map[AudioCodecFlag]string{
	1:    _AudioCodecFlag_name[0:4],
	2:    _AudioCodecFlag_name[4:9],
	4:    _AudioCodecFlag_name[9:12],
	8:    _AudioCodecFlag_name[12:17],
	16:   _AudioCodecFlag_name[17:23],
	32:   _AudioCodecFlag_name[23:29],
	64:   _AudioCodecFlag_name[29:34],
	128:  _AudioCodecFlag_name[34:39],
	256:  _AudioCodecFlag_name[39:44],
	512:  _AudioCodecFlag_name[44:51],
	1024: _AudioCodecFlag_name[51:54],
	2048: _AudioCodecFlag_name[54:59],
	4095: _AudioCodecFlag_name[59:62],
}

func (i AudioCodecFlag) String() string {
	if str, ok := _AudioCodecFlag_map[i]; ok {
		return str
	}
	return "AudioCodecFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
