// Code generated by "stringer -type VideoCodecFlag -trimprefix VideoCodecFlag -output cmd_netconnection_video_codec_flag_string_gen.go"; DO NOT EDIT.

package rtmp

import "strconv"

const (
	_VideoCodecFlag_name_0 = "UnusedJpeg"
	_VideoCodecFlag_name_1 = "Sorenson"
	_VideoCodecFlag_name_2 = "Homebrew"
	_VideoCodecFlag_name_3 = "Vp6"
	_VideoCodecFlag_name_4 = "Vp6alpha"
	_VideoCodecFlag_name_5 = "Homebrewv"
	_VideoCodecFlag_name_6 = "H264"
	_VideoCodecFlag_name_7 = "All"
)

var (
	_VideoCodecFlag_index_0 = [...]uint8{0, 6, 10}
)

func (i VideoCodecFlag) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _VideoCodecFlag_name_0[_VideoCodecFlag_index_0[i]:_VideoCodecFlag_index_0[i+1]]
	case i == 4:
		return _VideoCodecFlag_name_1
	case i == 8:
		return _VideoCodecFlag_name_2
	case i == 16:
		return _VideoCodecFlag_name_3
	case i == 32:
		return _VideoCodecFlag_name_4
	case i == 64:
		return _VideoCodecFlag_name_5
	case i == 128:
		return _VideoCodecFlag_name_6
	case i == 255:
		return _VideoCodecFlag_name_7
	default:
		return "VideoCodecFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
