// Code generated by "stringer -type EncodingAMFType -trimprefix EncodingAMFType -output cmd_netconnection_encoding_amf_type_string_gen.go"; DO NOT EDIT.

package rtmp

import "strconv"

const (
	_EncodingAMFType_name_0 = "AMF0"
	_EncodingAMFType_name_1 = "AMF3"
)

func (i EncodingAMFType) String() string {
	switch {
	case i == 0:
		return _EncodingAMFType_name_0
	case i == 3:
		return _EncodingAMFType_name_1
	default:
		return "EncodingAMFType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
