// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type NetStreamCommandHandler interface {
	OnOnStatus(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, onStatus OnStatus)
	OnPlay(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, play Play)
	OnPlay2(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, play2 Play2)
	OnDeleteStream(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, deleteStream DeleteStream)
	OnCloseStream(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, closeStream CloseStream)
	OnReceiveAudio(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, receiveAudio ReceiveAudio)
	OnReceiveVideo(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, receiveVideo ReceiveVideo)
	OnPublish(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, publish Publish)
	OnSeek(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, seek Seek)
	OnPause(ctx context.Context, chunkStreamID uint32, messageStreamID uint32, pause Pause)
}
