// Code generated by "stringer -type MessageTypeID -trimprefix MessageTypeID -output message_typeid_string_gen.go"; DO NOT EDIT.

package rtmp

import "strconv"

const (
	_MessageTypeID_name_0 = "SetChunkSizeAbortMessageAcknowledgementUserControlMessagesWindowAcknowledgementSizeSetPeerBandwidth"
	_MessageTypeID_name_1 = "AudioVideo"
	_MessageTypeID_name_2 = "DataAMF3SharedObjectAMF3CommandAMF3DataAMF0SharedObjectAMF0CommandAMF0"
	_MessageTypeID_name_3 = "Aggregate"
)

var (
	_MessageTypeID_index_0 = [...]uint8{0, 12, 24, 39, 58, 83, 99}
	_MessageTypeID_index_1 = [...]uint8{0, 5, 10}
	_MessageTypeID_index_2 = [...]uint8{0, 8, 24, 35, 43, 59, 70}
)

func (i MessageTypeID) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _MessageTypeID_name_0[_MessageTypeID_index_0[i]:_MessageTypeID_index_0[i+1]]
	case 8 <= i && i <= 9:
		i -= 8
		return _MessageTypeID_name_1[_MessageTypeID_index_1[i]:_MessageTypeID_index_1[i+1]]
	case 15 <= i && i <= 20:
		i -= 15
		return _MessageTypeID_name_2[_MessageTypeID_index_2[i]:_MessageTypeID_index_2[i+1]]
	case i == 22:
		return _MessageTypeID_name_3
	default:
		return "MessageTypeID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
