// Code generated by "stringer -type EventType -trimprefix EventType -output msg_user_control_event_type_string_gen.go"; DO NOT EDIT.

package rtmp

import "strconv"

const (
	_EventType_name_0 = "StreamBeginStreamEOFStreamDrySetBufferLengthStreamIsRecorded"
	_EventType_name_1 = "PingRequestPingResponse"
)

var (
	_EventType_index_0 = [...]uint8{0, 11, 20, 29, 44, 60}
	_EventType_index_1 = [...]uint8{0, 11, 23}
)

func (i EventType) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _EventType_name_0[_EventType_index_0[i]:_EventType_index_0[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _EventType_name_1[_EventType_index_1[i]:_EventType_index_1[i+1]]
	default:
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
