// Code generated by "stringer -type BandwidthLimitType -trimprefix BandwidthLimitType -output msg_protocol_control_bandwidth_limit_type_string_gen.go"; DO NOT EDIT.

package rtmp

import "strconv"

const _BandwidthLimitType_name = "HardSoftDynamic"

var _BandwidthLimitType_index = [...]uint8{0, 4, 8, 15}

func (i BandwidthLimitType) String() string {
	if i >= BandwidthLimitType(len(_BandwidthLimitType_index)-1) {
		return "BandwidthLimitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BandwidthLimitType_name[_BandwidthLimitType_index[i]:_BandwidthLimitType_index[i+1]]
}
