// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type ProtocolControlEventHandler interface {
	OnSetChunkSize(ctx context.Context, setChunkSize SetChunkSize) ConnError
	OnAbortMessage(ctx context.Context, abortMessage AbortMessage) ConnError
	OnAcknowledgement(ctx context.Context, acknowledgement Acknowledgement) ConnError
	OnWindowAcknowledgementSize(ctx context.Context, windowAcknowledgementSize WindowAcknowledgementSize) ConnError
	OnSetPeerBandwidth(ctx context.Context, setPeerBandwidth SetPeerBandwidth) ConnError
}
