// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type UserControlEventHandler interface {
	OnStreamBegin(ctx context.Context, streamBegin StreamBegin)
	OnStreamEOF(ctx context.Context, streamEOF StreamEOF)
	OnStreamDry(ctx context.Context, streamDry StreamDry)
	OnSetBufferLength(ctx context.Context, setBufferLength SetBufferLength)
	OnStreamIsRecorded(ctx context.Context, streamIsRecorded StreamIsRecorded)
	OnPingRequest(ctx context.Context, pingRequest PingRequest)
	OnPingResponse(ctx context.Context, pingResponse PingResponse)
}
