// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type UserControlEventHandler interface {
	OnStreamBegin(ctx context.Context, streamBegin StreamBegin) ConnError
	OnStreamEOF(ctx context.Context, streamEOF StreamEOF) ConnError
	OnStreamDry(ctx context.Context, streamDry StreamDry) ConnError
	OnSetBufferLength(ctx context.Context, setBufferLength SetBufferLength) ConnError
	OnStreamIsRecorded(ctx context.Context, streamIsRecorded StreamIsRecorded) ConnError
	OnPingRequest(ctx context.Context, pingRequest PingRequest) ConnError
	OnPingResponse(ctx context.Context, pingResponse PingResponse) ConnError
}
