// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type ProtocolControlEventHandler interface {
	OnSetChunkSize(ctx context.Context, setChunkSize SetChunkSize)
	OnAbortMessage(ctx context.Context, abortMessage AbortMessage)
	OnAcknowledgement(ctx context.Context, acknowledgement Acknowledgement)
	OnWindowAcknowledgementSize(ctx context.Context, windowAcknowledgementSize WindowAcknowledgementSize)
	OnSetPeerBandwidth(ctx context.Context, setPeerBandwidth SetPeerBandwidth)
}
