// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type ProtocolController interface {
	SetChunkSize(ctx context.Context, chunkSize uint32) error
	AbortMessage(ctx context.Context, chunkStreamID uint32) error
	Acknowledgement(ctx context.Context, sequenceNumber uint32) error
	WindowAcknowledgementSize(ctx context.Context, acknowledgementWindowSize uint32) error
	SetPeerBandwidth(ctx context.Context, acknowledgmentWindowSize uint32, limitType BandwidthLimitType) error
}
