// Automatically generated by go generate; DO NOT EDIT.

package rtmp

import (
	"context"
)

type UserController interface {
	StreamBegin(ctx context.Context, streamID uint32) error
	StreamEOF(ctx context.Context, streamID uint32) error
	StreamDry(ctx context.Context, streamID uint32) error
	SetBufferLength(ctx context.Context, streamID uint32, bufferLength uint32) error
	StreamIsRecorded(ctx context.Context, streamID uint32) error
	PingRequest(ctx context.Context, timestamp uint32) error
	PingResponse(ctx context.Context, timestamp uint32) error
}
